# Generated by Django 5.0.2 on 2024-02-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='loan',
            table='loan',
        ),
    ]
